export const CONFIG = {
  TOKEN: process.env.DISCORD_TOKEN,
  GUILD_ID: process.env.GUILD_ID,

  // Tickets
  TICKETS_CATEGORY_ID: process.env.TICKETS_CATEGORY_ID,
  STAFF_ROLE_ID: process.env.STAFF_ROLE_ID,
  STAFF_ALERT_CHANNEL_ID: process.env.STAFF_ALERT_CHANNEL_ID,
  TICKET_TRANSCRIPTS_CHANNEL_ID: process.env.TICKET_TRANSCRIPTS_CHANNEL_ID,
  CHANNELS: { VERIFICATION: process.env.VERIFICATION_CHANNEL_ID },

  // WL / Boas-vindas
  WELCOME_CHANNEL_ID: process.env.WELCOME_CHANNEL_ID,
  WL_STAFF_REVIEW_CHANNEL_ID: process.env.WL_STAFF_REVIEW_CHANNEL_ID,
  WL_APPROVED_ROLE_ID: process.env.WL_APPROVED_ROLE_ID,
  WL_NOTIFY_APPROVED_CHANNEL_ID: process.env.WL_NOTIFY_APPROVED_CHANNEL_ID,
  WL_NOTIFY_REJECTED_CHANNEL_ID: process.env.WL_NOTIFY_REJECTED_CHANNEL_ID
};
